export interface ShipVersionDTO {
    acceleration: number | null;
    armor_rating: number | null;
    base_value: number | null;
    center: string[] | null;
    cr_deployment_cost: number | null;
    cr_loss_per_sec: string | null;
    cr_recovery: string | null;
    data_hash: string;
    deceleration: number | null;
    designation: string | null;
    display_name: string | null;
    fighter_bays: number | null;
    flux_dissipation: number | null;
    fuel_per_ly: string | null;
    hints: string[] | null;
    hitpoints: number | null;
    major: number;
    manufacturer: string | null;
    mass: number | null;
    max_cargo: number | null;
    max_crew: number | null;
    max_flux: number | null;
    max_fuel: number | null;
    max_speed: number | null;
    max_turn_rate: number | null;
    min_crew: number | null;
    minor: number;
    mod_id: number;
    mod_name: string | null;
    mod_version_id: number;
    op_cost: number | null;
    patch: string;
    peak_cr_sec: number | null;
    phase_cost: number | null;
    phase_upkeep: number | null;
    shield_arc: number | null;
    shield_efficiency: string | null;
    shield_type: string;
    shield_type_id: number;
    shield_upkeep: string | null;
    ship_code: string;
    ship_id: number;
    ship_image_file_path: string | null;
    ship_instance_id: number;
    ship_size: string;
    ship_size_id: number;
    ship_system: string | null;
    ship_system_id: number | null;
    ship_version_id: number;
    tags: string[] | null;
    text1: string | null;
    text2: string | null;
    turn_acceleration: number | null;
}
