CREATE TABLE IF NOT EXISTS mods
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    display_name text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS mod_versions
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    mod_id integer NOT NULL,
    major integer NOT NULL,
    minor integer NOT NULL,
    patch text NOT NULL DEFAULT '0',
    data_changed boolean NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    UNIQUE (mod_id, major, minor, patch),
    FOREIGN KEY (mod_id) REFERENCES mods(id) ON DELETE CASCADE
);