CREATE TABLE IF NOT EXISTS weapon_types
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS weapon_sizes
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS damage_types
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS weapons
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    mod_id integer NOT NULL,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (mod_id, code),
    FOREIGN KEY (mod_id) REFERENCES mods(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weapon_instances
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    weapon_id integer NOT NULL,
    data_hash varchar(256) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (data_hash),
    FOREIGN KEY (weapon_id) REFERENCES weapons(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weapon_versions
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    mod_version_id integer NOT NULL,
    weapon_id integer NOT NULL,
    weapon_instance_id integer NOT NULL,
    turret_image_id integer,
    turret_gun_image_id integer,
    hardpoint_image_id integer,
    hardpoint_gun_image_id integer,
    PRIMARY KEY (id),
    UNIQUE (mod_version_id, weapon_id),
    FOREIGN KEY (mod_version_id) REFERENCES mod_versions(id) ON DELETE CASCADE,
    FOREIGN KEY (weapon_id) REFERENCES weapons(id) ON DELETE CASCADE,
    FOREIGN KEY (weapon_instance_id) REFERENCES weapon_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (turret_image_id) REFERENCES images(id),
    FOREIGN KEY (turret_gun_image_id) REFERENCES images(id),
    FOREIGN KEY (hardpoint_image_id) REFERENCES images(id),
    FOREIGN KEY (hardpoint_gun_image_id) REFERENCES images(id)
);

CREATE TABLE IF NOT EXISTS weapon_specs
(
    weapon_instance_id integer NOT NULL,
    weapon_type_id integer NOT NULL,
    weapon_size_id integer NOT NULL,
    damage_type_id integer NOT NULL,
    PRIMARY KEY (weapon_instance_id),
    FOREIGN KEY (weapon_instance_id) REFERENCES weapon_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (weapon_type_id) REFERENCES weapon_types(id),
    FOREIGN KEY (weapon_size_id) REFERENCES weapon_sizes(id),
    FOREIGN KEY (damage_type_id) REFERENCES damage_types(id)
);

CREATE TABLE IF NOT EXISTS weapon_stats
(
    weapon_instance_id integer NOT NULL,
    weapon_range integer,
    damage_per_shot integer,
    flux_per_shot numeric,
    emp integer,
    impact integer,
    turn_rate integer,
    op_cost integer,
    chargeup numeric,
    chargedown numeric,
    burst_size numeric,
    burst_delay numeric,
    min_spread numeric,
    max_spread numeric,
    spread_per_shot numeric,
    spread_decay_per_second numeric,
    autofire_accuracy_bonus integer,
    extra_arc_for_ai integer,
    base_value integer,
    PRIMARY KEY (weapon_instance_id),
    FOREIGN KEY (weapon_instance_id) REFERENCES weapon_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weapon_texts
(
    weapon_instance_id integer NOT NULL,
    display_name text,
    manufacturer text,
    primary_role_str text,
    proj_speed_str text,
    tracking_str text,
    turn_rate_str text,
    accuracy_str text,
    custom_primary text,
    custom_primary_hl text,
    custom_ancillary text,
    custom_ancillary_hl text,
    no_dps_tooltip boolean NOT NULL DEFAULT false,
    PRIMARY KEY (weapon_instance_id),
    FOREIGN KEY (weapon_instance_id) REFERENCES weapon_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weapon_descs (
    weapon_instance_id integer NOT NULL,
    text1 text,
    text2 text,
    PRIMARY KEY (weapon_instance_id),
    FOREIGN KEY (weapon_instance_id) REFERENCES weapon_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS proj_weapons
(
    weapon_instance_id integer NOT NULL,
    speed integer,
    launch_speed integer,
    flight_time numeric,
    hitpoints integer,
    PRIMARY KEY (weapon_instance_id),
    FOREIGN KEY (weapon_instance_id) REFERENCES weapon_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ammo_weapons
(
    weapon_instance_id integer NOT NULL,
    max_ammo integer NOT NULL,
    ammo_per_second numeric,
    reload_size integer NOT NULL DEFAULT 1,
    PRIMARY KEY (weapon_instance_id),
    FOREIGN KEY (weapon_instance_id) REFERENCES weapon_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS beam_weapons
(
    weapon_instance_id integer NOT NULL,
    beam_speed integer,
    damage_per_second integer,
    flux_per_second numeric,
    PRIMARY KEY (weapon_instance_id),
    FOREIGN KEY (weapon_instance_id) REFERENCES weapon_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weapon_hints
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS weapon_hint_junction
(
    weapon_instance_id integer NOT NULL,
    hint_id integer NOT NULL,
    PRIMARY KEY(weapon_instance_id, hint_id),
    FOREIGN KEY (weapon_instance_id) REFERENCES weapon_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (hint_id) REFERENCES weapon_hints(id)
);


CREATE TABLE IF NOT EXISTS weapon_tags
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS weapon_tag_junction
(
    weapon_instance_id integer NOT NULL,
    tag_id integer NOT NULL,
    PRIMARY KEY(weapon_instance_id, tag_id),
    FOREIGN KEY (weapon_instance_id) REFERENCES weapon_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES weapon_tags(id)
);

CREATE TABLE IF NOT EXISTS weapon_groups
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS weapon_group_junction
(
    weapon_instance_id integer NOT NULL,
    group_id integer NOT NULL,
    PRIMARY KEY (weapon_instance_id, group_id),
    FOREIGN KEY (weapon_instance_id) REFERENCES weapon_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES weapon_groups(id)
);