CREATE TABLE IF NOT EXISTS hullmods
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    mod_id integer NOT NULL,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (mod_id, code),
    FOREIGN KEY (mod_id) REFERENCES mods(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hullmod_instances
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    hullmod_id integer NOT NULL,
    data_hash varchar(256) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (data_hash),
    FOREIGN KEY (hullmod_id) REFERENCES hullmods(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hullmod_versions
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    mod_version_id integer NOT NULL,
    hullmod_id integer NOT NULL,
    hullmod_instance_id integer NOT NULL,
    hullmod_image_id integer,
    PRIMARY KEY (id),
    UNIQUE (mod_version_id, hullmod_id),
    UNIQUE (hullmod_instance_id, mod_version_id),
    FOREIGN KEY (mod_version_id) REFERENCES mod_versions(id) ON DELETE CASCADE,
    FOREIGN KEY (hullmod_id) REFERENCES hullmods(id) ON DELETE CASCADE,
    FOREIGN KEY (hullmod_instance_id) REFERENCES hullmod_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (hullmod_image_id) REFERENCES images(id)
);

CREATE TABLE IF NOT EXISTS hullmod_data (
    hullmod_instance_id integer NOT NULL,
    display_name text,
    manufacturer text,
    hullmod_desc text,
    base_value integer,
    cost_frigate integer NOT NULL DEFAULT 0,
    cost_destroyer integer NOT NULL DEFAULT 0,
    cost_cruiser integer NOT NULL DEFAULT 0,
    cost_capital integer NOT NULL DEFAULT 0,
    hide boolean NOT NULL DEFAULT false,
    hide_everywhere boolean NOT NULL DEFAULT false,
    PRIMARY KEY (hullmod_instance_id)
);


CREATE TABLE IF NOT EXISTS hullmod_tags
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS hullmod_tag_junction
(
    hullmod_instance_id integer NOT NULL,
    tag_id integer NOT NULL,
    PRIMARY KEY (hullmod_instance_id, tag_id),
    FOREIGN KEY (hullmod_instance_id) REFERENCES hullmod_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES hullmod_tags(id)
);

CREATE TABLE IF NOT EXISTS hullmod_ui_tags
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS hullmod_ui_tag_junction
(
    hullmod_instance_id integer NOT NULL,
    tag_id integer NOT NULL,
    PRIMARY KEY (hullmod_instance_id, tag_id),
    FOREIGN KEY (hullmod_instance_id) REFERENCES hullmod_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES hullmod_ui_tags(id)
);