CREATE TABLE IF NOT EXISTS ship_systems
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    mod_id integer NOT NULL,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (mod_id, code),
    FOREIGN KEY (mod_id) REFERENCES mods(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS ship_system_instances
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    ship_system_id integer NOT NULL,
    data_hash varchar(256) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (data_hash),
    FOREIGN KEY (ship_system_id) REFERENCES ship_systems(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ship_system_versions
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    mod_version_id integer NOT NULL,
    ship_system_id integer NOT NULL,
    ship_system_instance_id integer NOT NULL,
    ship_system_image_id integer,
    PRIMARY KEY (id),
    UNIQUE (mod_version_id, ship_system_id),
    FOREIGN KEY (mod_version_id) REFERENCES mod_versions(id) ON DELETE CASCADE,
    FOREIGN KEY (ship_system_id) REFERENCES ship_systems(id) ON DELETE CASCADE,
    FOREIGN KEY (ship_system_instance_id) REFERENCES ship_system_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (ship_system_image_id) REFERENCES images(id)
);

CREATE TABLE IF NOT EXISTS ship_system_data
(
    ship_system_instance_id integer NOT NULL,
    display_name text,
    PRIMARY KEY (ship_system_instance_id)
);

CREATE TABLE IF NOT EXISTS ship_system_desc
(
    ship_system_instance_id integer NOT NULL,
    text1 text,
    text2 text,
    text3 text,
    PRIMARY KEY (ship_system_instance_id)
);

