CREATE TABLE IF NOT EXISTS mount_types
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS shield_types
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS ship_sizes
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS ships
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    mod_id integer NOT NULL,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (id, mod_id),
    UNIQUE (mod_id, code),
    FOREIGN KEY (mod_id) REFERENCES mods(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ship_instances
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    ship_id integer NOT NULL,
    data_hash varchar(256) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (data_hash),
    UNIQUE(ship_id, id),
    FOREIGN KEY (ship_id) REFERENCES ships(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ship_versions
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    mod_version_id integer NOT NULL,
    ship_id integer NOT NULL,
    ship_instance_id integer NOT NULL,
    ship_image_id integer,
    PRIMARY KEY (id),
    UNIQUE (mod_version_id, ship_id),
    UNIQUE (ship_id, ship_instance_id, id),
    FOREIGN KEY (mod_version_id) REFERENCES mod_versions(id) ON DELETE CASCADE,
    FOREIGN KEY (ship_id, ship_instance_id) REFERENCES ship_instances(ship_id, id) ON DELETE CASCADE,
    FOREIGN KEY (ship_image_id) REFERENCES images(id)
);

CREATE TABLE IF NOT EXISTS ship_specs
(
    ship_instance_id integer NOT NULL,
    ship_size_id integer NOT NULL,
    shield_type_id integer NOT NULL,
    ship_system_id integer,
    defense_code text,
    PRIMARY KEY (ship_instance_id),
    FOREIGN KEY (ship_instance_id) REFERENCES ship_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (ship_size_id) REFERENCES ship_sizes(id),
    FOREIGN KEY (shield_type_id) REFERENCES shield_types(id),
    FOREIGN KEY (ship_system_id) REFERENCES ship_systems(id)
);

CREATE TABLE IF NOT EXISTS ship_stats
(
    ship_instance_id integer NOT NULL,
    hitpoints integer,
    armor_rating integer,
    max_flux integer,
    flux_dissipation integer,
    op_cost integer,
    fighter_bays integer,
    max_speed integer,
    acceleration integer,
    deceleration integer,
    max_turn_rate integer,
    turn_acceleration integer,
    mass integer,
    PRIMARY KEY (ship_instance_id),
    FOREIGN KEY (ship_instance_id) REFERENCES ship_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ship_texts
(
    ship_instance_id integer NOT NULL,
    display_name text,
    manufacturer text,
    designation text,
    base_value integer,
    PRIMARY KEY (ship_instance_id),
    FOREIGN KEY (ship_instance_id) REFERENCES ship_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ship_descs (
    ship_instance_id integer NOT NULL,
    text1 text,
    text2 text,
    PRIMARY KEY (ship_instance_id),
    FOREIGN KEY (ship_instance_id) REFERENCES ship_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ship_positions (
    ship_instance_id integer NOT NULL,
    x numeric NOT NULL,
    y numeric NOT NULL,
    PRIMARY KEY (ship_instance_id),
    FOREIGN KEY (ship_instance_id) REFERENCES ship_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ship_logistic_stats
(
    ship_instance_id integer NOT NULL,
    min_crew integer,
    max_crew integer,
    max_cargo integer,
    max_fuel integer,
    fuel_per_ly numeric,
    cr_recovery numeric,
    cr_deployment_cost integer,
    peak_cr_sec integer,
    cr_loss_per_sec numeric,
    PRIMARY KEY (ship_instance_id),
    FOREIGN KEY (ship_instance_id) REFERENCES ship_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ship_weapon_slots
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    ship_instance_id integer NOT NULL,
    weapon_size_id integer NOT NULL,
    weapon_type_id integer NOT NULL,
    mount_type_id integer NOT NULL,
    angle numeric NOT NULL,
    arc numeric NOT NULL,
    x numeric NOT NULL,
    y numeric NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (id, ship_instance_id),
    UNIQUE (ship_instance_id, code),
    FOREIGN KEY (ship_instance_id) REFERENCES ship_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (weapon_size_id) REFERENCES weapon_sizes(id),
    FOREIGN KEY (weapon_type_id) REFERENCES weapon_types(id),
    FOREIGN KEY (mount_type_id) REFERENCES mount_types(id)
);

CREATE TABLE IF NOT EXISTS shield_stats
(
    ship_instance_id integer NOT NULL,
    arc integer,
    upkeep numeric,
    efficiency numeric,
    PRIMARY KEY (ship_instance_id),
    FOREIGN KEY (ship_instance_id) REFERENCES ship_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS phase_stats
(
    ship_instance_id integer NOT NULL,
    cost integer,
    upkeep integer,
    PRIMARY KEY (ship_instance_id),
    FOREIGN KEY (ship_instance_id) REFERENCES ship_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ship_hints
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS ship_hint_junction
(
    ship_instance_id integer NOT NULL,
    hint_id integer NOT NULL,
    PRIMARY KEY (ship_instance_id, hint_id),
    FOREIGN KEY (ship_instance_id) REFERENCES ship_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (hint_id) REFERENCES ship_hints(id)
);

CREATE TABLE IF NOT EXISTS ship_tags
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS ship_tag_junction
(
    ship_instance_id integer NOT NULL,
    tag_id integer NOT NULL,
    PRIMARY KEY (ship_instance_id, tag_id),
    FOREIGN KEY (ship_instance_id) REFERENCES ship_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES ship_tags(id)
);

