CREATE TABLE IF NOT EXISTS wing_formations
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS wing_roles
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS wing_instances
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    ship_id integer NOT NULL,
    data_hash varchar(256) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (data_hash),
    FOREIGN KEY (ship_id) REFERENCES ships(id)
);

CREATE TABLE IF NOT EXISTS wing_versions
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    mod_version_id integer NOT NULL,
    ship_id integer NOT NULL,
    wing_instance_id integer NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (mod_version_id, ship_id),
    FOREIGN KEY (mod_version_id) REFERENCES mod_versions(id) ON DELETE CASCADE,
    FOREIGN KEY (ship_id) REFERENCES ships(id) ON DELETE CASCADE,
    FOREIGN KEY (wing_instance_id) REFERENCES wing_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wing_data
(
    wing_instance_id integer NOT NULL,
    formation_id integer NOT NULL,
    role_id integer NOT NULL,
    role_desc text,
    op_cost integer,
    deployment_range integer,
    num_fighters integer,
    refit_time integer,
    base_value integer,
    vents integer NOT NULL DEFAULT 0,
    capacitors integer NOT NULL DEFAULT 0,
    PRIMARY KEY (wing_instance_id),
    FOREIGN KEY (wing_instance_id) REFERENCES wing_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (formation_id) REFERENCES wing_formations(id),
    FOREIGN KEY (role_id) REFERENCES wing_roles(id)
);

CREATE TABLE IF NOT EXISTS wing_hullmods
(
    wing_instance_id integer NOT NULL,
    hullmod_id integer NOT NULL,
    PRIMARY KEY (wing_instance_id),
    FOREIGN KEY (wing_instance_id) REFERENCES wing_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (hullmod_id) REFERENCES hullmods(id)
);

CREATE TABLE IF NOT EXISTS wing_weapon_groups
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    wing_instance_id integer NOT NULL,
    mode text,
    PRIMARY KEY (id),
    FOREIGN KEY (wing_instance_id) REFERENCES wing_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wing_weapons
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    wing_weapon_group_id integer NOT NULL,
    weapon_slot_code text NOT NULL,
    weapon_id integer NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (wing_weapon_group_id, weapon_slot_code),
    FOREIGN KEY (wing_weapon_group_id) REFERENCES wing_weapon_groups(id) ON DELETE CASCADE,
    FOREIGN KEY (weapon_id) REFERENCES weapons(id)
);

CREATE TABLE IF NOT EXISTS wing_tags
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS wing_tag_junction
(
    wing_instance_id integer NOT NULL,
    tag_id integer NOT NULL,
    PRIMARY KEY (wing_instance_id, tag_id),
    FOREIGN KEY (wing_instance_id) REFERENCES wing_instances(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES wing_tags(id)
);