CREATE TABLE IF NOT EXISTS users
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS entity_types
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS entity_comments
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    entity_type_id integer NOT NULL,
    entity_code text NOT NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (entity_type_id) REFERENCES entity_types(id)
);

CREATE TABLE IF NOT EXISTS builds
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    mod_version_id integer NOT NULL,
    entity_id integer NOT NULL,
    title text NOT NULL,
    content text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (entity_id) REFERENCES entity_types(id)
);

CREATE TABLE IF NOT EXISTS build_stats
(
    build_id integer NOT NULL,
    vents integer NOT NULL DEFAULT 0,
    capacitors integer NOT NULL DEFAULT 0,
    PRIMARY KEY (build_id),
    FOREIGN KEY (build_id) REFERENCES builds(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS build_weapons
(
    build_id integer NOT NULL,
    ship_weapon_slot_id integer NOT NULL,
    weapon_id integer NOT NULL,
    PRIMARY KEY (build_id, ship_weapon_slot_id),
    FOREIGN KEY (build_id) REFERENCES builds(id) ON DELETE CASCADE,
    FOREIGN KEY (ship_weapon_slot_id) REFERENCES ship_weapon_slots(id),
    FOREIGN KEY (weapon_id) REFERENCES weapons(id)
);

CREATE TABLE IF NOT EXISTS build_hullmods
(
    build_id integer NOT NULL,
    hullmod_id integer NOT NULL,
    PRIMARY KEY (build_id, hullmod_id),
    FOREIGN KEY (build_id) REFERENCES builds(id) ON DELETE CASCADE,
    FOREIGN KEY (hullmod_id) REFERENCES hullmods(id)
);

CREATE TABLE IF NOT EXISTS build_wings
(
    build_id integer NOT NULL,
    ship_weapon_slot_id integer NOT NULL,
    ship_id integer NOT NULL,
    PRIMARY KEY (build_id, ship_weapon_slot_id),
    FOREIGN KEY (build_id) REFERENCES builds(id) ON DELETE CASCADE,
    FOREIGN KEY (ship_weapon_slot_id) REFERENCES ship_weapon_slots(id),
    FOREIGN KEY (ship_id) REFERENCES ships(id)
);

CREATE TABLE IF NOT EXISTS build_comments
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    build_id integer NOT NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (build_id) REFERENCES builds(id) ON DELETE CASCADE
);