CREATE TABLE IF NOT EXISTS builds
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    ship_id integer NOT NULL,
    ship_version_id integer NOT NULL,
    ship_instance_id integer NOT NULL,
    title text NOT NULL,
    content text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (ship_version_id, id),
    UNIQUE (ship_instance_id, id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (ship_id, ship_instance_id, ship_version_id) 
        REFERENCES ship_versions(ship_id, ship_instance_id, id)
);

CREATE TABLE IF NOT EXISTS build_mod_versions(
    build_id integer NOT NULL,
    mod_version_id integer NOT NULL,
    mod_id integer NOT NULL,
    PRIMARY KEY (build_id, mod_id),
    UNIQUE (build_id, mod_version_id),
    FOREIGN KEY (build_id) REFERENCES builds(id),
    FOREIGN KEY (mod_version_id, mod_id) REFERENCES mod_versions(id, mod_id)
);

CREATE TABLE IF NOT EXISTS build_stats
(
    build_id integer NOT NULL,
    vents integer NOT NULL DEFAULT 0,
    capacitors integer NOT NULL DEFAULT 0,
    PRIMARY KEY (build_id),
    FOREIGN KEY (build_id) REFERENCES builds(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS build_weapons
(
    build_id integer NOT NULL,
    mod_version_id integer NOT NULL,
    ship_instance_id integer NOT NULL,
    ship_weapon_slot_id integer NOT NULL,
    weapon_instance_id integer NOT NULL,

    PRIMARY KEY (build_id, ship_weapon_slot_id),

    -- Start with build_id and mod_version_id
    FOREIGN KEY (build_id, mod_version_id)
        REFERENCES build_mod_versions(build_id, mod_version_id)
        ON DELETE CASCADE,

    -- Bind ship_instance_id to build_id 
    FOREIGN KEY (ship_instance_id, build_id)
        REFERENCES builds(ship_instance_id, id),

    -- Bind ship_weapon_slot_id to ship_instance_id
    FOREIGN KEY (ship_weapon_slot_id, ship_instance_id)
        REFERENCES ship_weapon_slots(id, ship_instance_id),

    -- Bind weapon_instance_id to mod_version_id
    FOREIGN KEY (weapon_instance_id, mod_version_id)
        REFERENCES weapon_versions(weapon_instance_id, mod_version_id)
);

CREATE TABLE IF NOT EXISTS build_hullmods
(
    build_id integer NOT NULL,
    mod_version_id integer NOT NULL,
    hullmod_instance_id integer NOT NULL,

    PRIMARY KEY (build_id, hullmod_instance_id),

    -- Start with build_id and mod_version_id
    FOREIGN KEY (build_id, mod_version_id)
        REFERENCES build_mod_versions(build_id, mod_version_id)
        ON DELETE CASCADE,

    -- Bind hullmod_instance_id to mod_version_id
    FOREIGN KEY (hullmod_instance_id, mod_version_id)
        REFERENCES hullmod_versions(hullmod_instance_id, mod_version_id)
);

CREATE TABLE IF NOT EXISTS build_wings
(
    build_id integer NOT NULL,
    mod_version_id integer NOT NULL,
    ship_instance_id integer NOT NULL,
    ship_weapon_slot_id integer NOT NULL,
    wing_instance_id integer NOT NULL,

    PRIMARY KEY (build_id, ship_weapon_slot_id),

    -- Start with build_id and mod_version_id
    FOREIGN KEY (build_id, mod_version_id)
        REFERENCES build_mod_versions(build_id, mod_version_id)
        ON DELETE CASCADE,

    -- Bind ship_instance_id to build_id 
    FOREIGN KEY (ship_instance_id, build_id)
        REFERENCES builds(ship_instance_id, id),

    -- Bind ship_weapon_slot_id to ship_instance_id
    FOREIGN KEY (ship_weapon_slot_id, ship_instance_id)
        REFERENCES ship_weapon_slots(id, ship_instance_id),

    -- Bind wing_instance_id to mod_version_id
    FOREIGN KEY (wing_instance_id, mod_version_id)
        REFERENCES wing_versions(wing_instance_id, mod_version_id)
);

CREATE TABLE IF NOT EXISTS build_comments
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    build_id integer NOT NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (build_id) REFERENCES builds(id) ON DELETE CASCADE
);
