export type HullmodVersionDTO = {
    base_value: number | null;
    cost_capital: number | null;
    cost_cruiser: number | null;
    cost_destroyer: number | null;
    cost_frigate: number | null;
    data_hash: string | null;
    display_name: string | null;
    hide: boolean | null;
    hide_everywhere: boolean | null;
    hullmod_code: string | null;
    hullmod_desc: string | null;
    hullmod_id: number | null;
    hullmod_image_file_path: string | null;
    hullmod_instance_id: number | null;
    hullmod_version_id: number | null;
    major: number | null;
    manufacturer: string | null;
    minor: number | null;
    mod_id: number | null;
    mod_name: string | null;
    mod_version_id: number | null;
    patch: string | null;
    tags: string[] | null;
    ui_tags: string[] | null;
};
