-- Mods
DROP TABLE IF EXISTS mod_versions CASCADE;
DROP TABLE IF EXISTS mods CASCADE;
--

-- Images
DROP TABLE IF EXISTS images CASCADE;
--

-- Weapons
DROP TABLE IF EXISTS weapon_group_junction CASCADE;
DROP TABLE IF EXISTS weapon_groups CASCADE;
DROP TABLE IF EXISTS weapon_tag_junction CASCADE;
DROP TABLE IF EXISTS weapon_tags CASCADE;
DROP TABLE IF EXISTS weapon_hint_junction CASCADE;
DROP TABLE IF EXISTS weapon_hints CASCADE;

DROP TABLE IF EXISTS beam_weapons CASCADE;
DROP TABLE IF EXISTS ammo_weapons CASCADE;
DROP TABLE IF EXISTS proj_weapons CASCADE;

DROP TABLE IF EXISTS weapon_descs CASCADE;
DROP TABLE IF EXISTS weapon_texts CASCADE;
DROP TABLE IF EXISTS weapon_stats CASCADE;
DROP TABLE IF EXISTS weapon_specs CASCADE;

DROP TABLE IF EXISTS weapon_versions CASCADE;
DROP TABLE IF EXISTS weapon_instances CASCADE;
DROP TABLE IF EXISTS weapons CASCADE;

DROP TABLE IF EXISTS weapon_sizes CASCADE;
DROP TABLE IF EXISTS weapon_types CASCADE;
DROP TABLE IF EXISTS damage_types CASCADE;
--

-- Hullmods
DROP TABLE IF EXISTS hullmod_ui_tags CASCADE;
DROP TABLE IF EXISTS hullmod_ui_tag_junction CASCADE;
DROP TABLE IF EXISTS hullmod_versions CASCADE;
DROP TABLE IF EXISTS hullmod_instances CASCADE;
DROP TABLE IF EXISTS hullmods CASCADE;
--

-- Ship Systems
DROP TABLE IF EXISTS ship_system_desc CASCADE;
DROP TABLE IF EXISTS ship_system_data CASCADE;
DROP TABLE IF EXISTS ship_system_versions CASCADE;
DROP TABLE IF EXISTS ship_system_instances CASCADE;
DROP TABLE IF EXISTS ship_systems CASCADE;
--

-- Ships
DROP TABLE IF EXISTS built_in_wings CASCADE;
DROP TABLE IF EXISTS built_in_hullmods CASCADE;
DROP TABLE IF EXISTS built_in_weapons CASCADE;

DROP TABLE IF EXISTS ship_tag_junction CASCADE;
DROP TABLE IF EXISTS ship_tags CASCADE;
DROP TABLE IF EXISTS ship_hint_junction CASCADE;
DROP TABLE IF EXISTS ship_hints CASCADE;

DROP TABLE IF EXISTS phase_stats CASCADE;
DROP TABLE IF EXISTS shield_stats CASCADE;
DROP TABLE IF EXISTS ship_weapon_slots CASCADE;
DROP TABLE IF EXISTS mount_types CASCADE;
DROP TABLE IF EXISTS ship_logistic_stats CASCADE;
DROP TABLE IF EXISTS ship_texts CASCADE;
DROP TABLE IF EXISTS ship_descs CASCADE;
DROP TABLE IF EXISTS ship_stats CASCADE;

DROP TABLE IF EXISTS ship_versions CASCADE;
DROP TABLE IF EXISTS ship_instances CASCADE;
DROP TABLE IF EXISTS ships CASCADE;

DROP TABLE IF EXISTS ship_sizes CASCADE;
DROP TABLE IF EXISTS shield_types CASCADE;
DROP TABLE IF EXISTS mount_types CASCADE;
--

-- Wings
DROP TABLE IF EXISTS wing_tag_junction CASCADE;
DROP TABLE IF EXISTS wing_tags CASCADE;

DROP TABLE IF EXISTS wing_weapons CASCADE;
DROP TABLE IF EXISTS wing_weapon_groups CASCADE;
DROP TABLE IF EXISTS wing_hullmods CASCADE;
DROP TABLE IF EXISTS wing_data CASCADE;

DROP TABLE IF EXISTS wing_versions CASCADE;
DROP TABLE IF EXISTS wing_instances CASCADE;

DROP TABLE IF EXISTS wing_roles CASCADE;
DROP TABLE IF EXISTS wing_formations CASCADE;
--

-- Users
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS entity_types CASCADE;
DROP TABLE IF EXISTS entity_comments CASCADE;
DROP TABLE IF EXISTS builds CASCADE;
DROP TABLE IF EXISTS build_stats CASCADE;
DROP TABLE IF EXISTS build_weapons CASCADE;
DROP TABLE IF EXISTS build_wings CASCADE;
DROP TABLE IF EXISTS build_hullmods CASCADE;
DROP TABLE IF EXISTS build_comments CASCADE;
--