/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AllHullmodInstances {
  base_value: number | null;
  cost_capital: number | null;
  cost_cruiser: number | null;
  cost_destroyer: number | null;
  cost_frigate: number | null;
  data_hash: string | null;
  display_name: string | null;
  hide: boolean | null;
  hide_everywhere: boolean | null;
  hullmod_desc: string | null;
  hullmod_id: number | null;
  hullmod_instance_id: number | null;
  manufacturer: string | null;
  tags: string[] | null;
  ui_tags: string[] | null;
}

export interface AmmoWeapons {
  ammo_per_second: Numeric | null;
  max_ammo: number;
  reload_size: Generated<number>;
  weapon_instance_id: number;
}

export interface BeamWeapons {
  beam_speed: number | null;
  damage_per_second: number | null;
  flux_per_second: Numeric | null;
  weapon_instance_id: number;
}

export interface BuildComments {
  build_id: number;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  user_id: number;
}

export interface BuildHullmods {
  build_id: number;
  hullmod_id: number;
}

export interface Builds {
  content: string | null;
  created_at: Generated<Timestamp>;
  entity_id: number;
  id: Generated<number>;
  mod_version_id: number;
  title: string;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface BuildStats {
  build_id: number;
  capacitors: Generated<number>;
  vents: Generated<number>;
}

export interface BuildWeapons {
  build_id: number;
  ship_weapon_slot_id: number;
  weapon_id: number;
}

export interface BuildWings {
  build_id: number;
  ship_id: number;
  ship_weapon_slot_id: number;
}

export interface BuiltInHullmods {
  hullmod_id: number;
  ship_instance_id: number;
}

export interface BuiltInWeapons {
  ship_instance_id: number;
  slot_code: string;
  weapon_id: number;
}

export interface BuiltInWings {
  num_wings: number;
  ship_id: number;
  ship_instance_id: number;
}

export interface DamageTypes {
  code: string;
  id: Generated<number>;
}

export interface EntityComments {
  content: string;
  created_at: Generated<Timestamp>;
  entity_code: string;
  entity_type_id: number;
  id: Generated<number>;
  user_id: number;
}

export interface EntityTypes {
  code: string;
  id: Generated<number>;
}

export interface HullmodData {
  base_value: number | null;
  cost_capital: Generated<number>;
  cost_cruiser: Generated<number>;
  cost_destroyer: Generated<number>;
  cost_frigate: Generated<number>;
  display_name: string | null;
  hide: Generated<boolean>;
  hide_everywhere: Generated<boolean>;
  hullmod_desc: string | null;
  hullmod_instance_id: number;
  manufacturer: string | null;
}

export interface HullmodInstances {
  data_hash: string;
  hullmod_id: number;
  id: Generated<number>;
}

export interface Hullmods {
  code: string;
  id: Generated<number>;
  mod_id: number;
}

export interface HullmodTagJunction {
  hullmod_instance_id: number;
  tag_id: number;
}

export interface HullmodTags {
  code: string;
  id: Generated<number>;
}

export interface HullmodUiTagJunction {
  hullmod_instance_id: number;
  tag_id: number;
}

export interface HullmodUiTags {
  code: string;
  id: Generated<number>;
}

export interface HullmodVersions {
  hullmod_id: number;
  hullmod_image_id: number | null;
  hullmod_instance_id: number;
  id: Generated<number>;
  mod_version_id: number;
}

export interface Images {
  file_hash: string;
  file_path: string;
  id: Generated<number>;
}

export interface Mods {
  code: string;
  display_name: string;
  id: Generated<number>;
}

export interface ModVersions {
  data_changed: Generated<boolean>;
  id: Generated<number>;
  major: number;
  minor: number;
  mod_id: number;
  patch: Generated<string>;
}

export interface MountTypes {
  code: string;
  id: Generated<number>;
}

export interface PhaseStats {
  cost: number | null;
  ship_instance_id: number;
  upkeep: number | null;
}

export interface ProjWeapons {
  flight_time: Numeric | null;
  hitpoints: number | null;
  launch_speed: number | null;
  speed: number | null;
  weapon_instance_id: number;
}

export interface ShieldStats {
  arc: number | null;
  efficiency: Numeric | null;
  ship_instance_id: number;
  upkeep: Numeric | null;
}

export interface ShieldTypes {
  code: string;
  id: Generated<number>;
}

export interface ShipDescs {
  ship_instance_id: number;
  text1: string | null;
  text2: string | null;
}

export interface ShipHintJunction {
  hint_id: number;
  ship_instance_id: number;
}

export interface ShipHints {
  code: string;
  id: Generated<number>;
}

export interface ShipInstances {
  data_hash: string;
  id: Generated<number>;
  ship_id: number;
}

export interface ShipLogisticStats {
  cr_deployment_cost: number | null;
  cr_loss_per_sec: Numeric | null;
  cr_recovery: Numeric | null;
  fuel_per_ly: Numeric | null;
  max_cargo: number | null;
  max_crew: number | null;
  max_fuel: number | null;
  min_crew: number | null;
  peak_cr_sec: number | null;
  ship_instance_id: number;
}

export interface ShipPositions {
  center: ArrayType<Numeric> | null;
  ship_instance_id: number;
}

export interface Ships {
  code: string;
  id: Generated<number>;
  mod_id: number;
}

export interface ShipSizes {
  code: string;
  id: Generated<number>;
}

export interface ShipSpecs {
  defense_code: string | null;
  shield_type_id: number;
  ship_instance_id: number;
  ship_size_id: number;
  ship_system_id: number | null;
}

export interface ShipStats {
  acceleration: number | null;
  armor_rating: number | null;
  deceleration: number | null;
  fighter_bays: number | null;
  flux_dissipation: number | null;
  hitpoints: number | null;
  mass: number | null;
  max_flux: number | null;
  max_speed: number | null;
  max_turn_rate: number | null;
  op_cost: number | null;
  ship_instance_id: number;
  turn_acceleration: number | null;
}

export interface ShipSystemData {
  display_name: string | null;
  ship_system_instance_id: number;
}

export interface ShipSystemDesc {
  ship_system_instance_id: number;
  text1: string | null;
  text2: string | null;
  text3: string | null;
}

export interface ShipSystemDescs {
  ship_system_instance_id: number;
  text1: string | null;
  text2: string | null;
  text3: string | null;
}

export interface ShipSystemInstances {
  data_hash: string;
  id: Generated<number>;
  ship_system_id: number;
}

export interface ShipSystems {
  code: string;
  id: Generated<number>;
  mod_id: number;
}

export interface ShipSystemVersions {
  id: Generated<number>;
  mod_version_id: number;
  ship_system_id: number;
  ship_system_image_id: number | null;
  ship_system_instance_id: number;
}

export interface ShipTagJunction {
  ship_instance_id: number;
  tag_id: number;
}

export interface ShipTags {
  code: string;
  id: Generated<number>;
}

export interface ShipTexts {
  base_value: number | null;
  designation: string | null;
  display_name: string | null;
  manufacturer: string | null;
  ship_instance_id: number;
}

export interface ShipVersions {
  id: Generated<number>;
  mod_version_id: number;
  ship_id: number;
  ship_image_id: number | null;
  ship_instance_id: number;
}

export interface ShipVersionsFull {
  acceleration: number | null;
  armor_rating: number | null;
  base_value: number | null;
  center: ArrayType<Numeric> | null;
  cr_deployment_cost: number | null;
  cr_loss_per_sec: Numeric | null;
  cr_recovery: Numeric | null;
  data_hash: string | null;
  deceleration: number | null;
  designation: string | null;
  display_name: string | null;
  fighter_bays: number | null;
  flux_dissipation: number | null;
  fuel_per_ly: Numeric | null;
  hints: string[] | null;
  hitpoints: number | null;
  major: number | null;
  manufacturer: string | null;
  mass: number | null;
  max_cargo: number | null;
  max_crew: number | null;
  max_flux: number | null;
  max_fuel: number | null;
  max_speed: number | null;
  max_turn_rate: number | null;
  min_crew: number | null;
  minor: number | null;
  mod_id: number | null;
  mod_name: string | null;
  mod_version_id: number | null;
  op_cost: number | null;
  patch: string | null;
  peak_cr_sec: number | null;
  phase_cost: number | null;
  phase_upkeep: number | null;
  shield_arc: number | null;
  shield_efficiency: Numeric | null;
  shield_type: string | null;
  shield_type_id: number | null;
  shield_upkeep: Numeric | null;
  ship_id: number | null;
  ship_image_file_path: string | null;
  ship_instance_id: number | null;
  ship_size: string | null;
  ship_size_id: number | null;
  ship_system: string | null;
  ship_system_id: number | null;
  ship_version_id: number | null;
  tags: string[] | null;
  text1: string | null;
  text2: string | null;
  turn_acceleration: number | null;
}

export interface ShipWeaponSlots {
  angle: Numeric;
  arc: Numeric;
  code: string;
  id: Generated<number>;
  mount_type_id: number;
  position: ArrayType<Numeric>;
  ship_instance_id: number;
  weapon_size_id: number;
  weapon_type_id: number;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  password_hash: string;
  username: string;
}

export interface WeaponDescs {
  text1: string | null;
  text2: string | null;
  weapon_instance_id: number;
}

export interface WeaponGroupJunction {
  group_id: number;
  weapon_instance_id: number;
}

export interface WeaponGroups {
  code: string;
  id: Generated<number>;
}

export interface WeaponHintJunction {
  hint_id: number;
  weapon_instance_id: number;
}

export interface WeaponHints {
  code: string;
  id: Generated<number>;
}

export interface WeaponInstances {
  data_hash: string;
  id: Generated<number>;
  weapon_id: number;
}

export interface Weapons {
  code: string;
  id: Generated<number>;
  mod_id: number;
}

export interface WeaponSizes {
  code: string;
  id: Generated<number>;
}

export interface WeaponSpecs {
  damage_type_id: number;
  weapon_instance_id: number;
  weapon_size_id: number;
  weapon_type_id: number;
}

export interface WeaponStats {
  autofire_accuracy_bonus: number | null;
  base_value: number | null;
  burst_delay: Numeric | null;
  burst_size: Numeric | null;
  chargedown: Numeric | null;
  chargeup: Numeric | null;
  damage_per_shot: number | null;
  emp: number | null;
  extra_arc_for_ai: number | null;
  flux_per_shot: Numeric | null;
  impact: number | null;
  max_spread: Numeric | null;
  min_spread: Numeric | null;
  op_cost: number | null;
  spread_decay_per_second: Numeric | null;
  spread_per_shot: Numeric | null;
  turn_rate: Numeric | null;
  weapon_instance_id: number;
  weapon_range: number | null;
}

export interface WeaponTagJunction {
  tag_id: number;
  weapon_instance_id: number;
}

export interface WeaponTags {
  code: string;
  id: Generated<number>;
}

export interface WeaponTexts {
  accuracy_str: string | null;
  custom_ancillary: string | null;
  custom_ancillary_hl: string | null;
  custom_primary: string | null;
  custom_primary_hl: string | null;
  display_name: string | null;
  manufacturer: string | null;
  no_dps_tooltip: Generated<boolean>;
  primary_role_str: string | null;
  proj_speed_str: string | null;
  tracking_str: string | null;
  turn_rate_str: string | null;
  weapon_instance_id: number;
}

export interface WeaponTypes {
  code: string;
  id: Generated<number>;
}

export interface WeaponVersions {
  hardpoint_gun_image_id: number | null;
  hardpoint_image_id: number | null;
  id: Generated<number>;
  mod_version_id: number;
  turret_gun_image_id: number | null;
  turret_image_id: number | null;
  weapon_id: number;
  weapon_instance_id: number;
}

export interface WeaponVersionsFull {
  accuracy_str: string | null;
  ammo_per_second: Numeric | null;
  autofire_accuracy_bonus: number | null;
  base_value: number | null;
  beam_speed: number | null;
  burst_delay: Numeric | null;
  burst_size: Numeric | null;
  chargedown: Numeric | null;
  chargeup: Numeric | null;
  custom_ancillary: string | null;
  custom_ancillary_hl: string | null;
  custom_primary: string | null;
  custom_primary_hl: string | null;
  damage_per_second: number | null;
  damage_per_shot: number | null;
  damage_type: string | null;
  damage_type_id: number | null;
  data_hash: string | null;
  display_name: string | null;
  emp: number | null;
  extra_arc_for_ai: number | null;
  flight_time: Numeric | null;
  flux_per_second: Numeric | null;
  flux_per_shot: Numeric | null;
  groups: string[] | null;
  hints: string[] | null;
  hitpoints: number | null;
  impact: number | null;
  launch_speed: number | null;
  major: number | null;
  manufacturer: string | null;
  max_ammo: number | null;
  max_spread: Numeric | null;
  min_spread: Numeric | null;
  minor: number | null;
  mod_id: number | null;
  mod_name: string | null;
  mod_version_id: number | null;
  no_dps_tooltip: boolean | null;
  op_cost: number | null;
  patch: string | null;
  primary_role_str: string | null;
  proj_speed_str: string | null;
  reload_size: number | null;
  speed: number | null;
  spread_decay_per_second: Numeric | null;
  spread_per_shot: Numeric | null;
  tags: string[] | null;
  text1: string | null;
  text2: string | null;
  tracking_str: string | null;
  turn_rate: Numeric | null;
  turn_rate_str: string | null;
  turret_gun_image_file_path: string | null;
  turret_image_file_path: string | null;
  weapon_id: number | null;
  weapon_instance_id: number | null;
  weapon_range: number | null;
  weapon_size: string | null;
  weapon_size_id: number | null;
  weapon_type: string | null;
  weapon_type_id: number | null;
  weapon_version_id: number | null;
}

export interface WingData {
  base_value: number | null;
  capacitors: Generated<number>;
  deployment_range: number | null;
  formation_id: number;
  num_fighters: number | null;
  op_cost: number | null;
  refit_time: number | null;
  role_desc: string | null;
  role_id: number;
  vents: Generated<number>;
  wing_instance_id: number;
}

export interface WingFormations {
  code: string;
  id: Generated<number>;
}

export interface WingHullmods {
  hullmod_id: number;
  wing_instance_id: number;
}

export interface WingInstances {
  data_hash: string;
  id: Generated<number>;
  ship_id: number;
}

export interface WingRoles {
  code: string;
  id: Generated<number>;
}

export interface WingTagJunction {
  tag_id: number;
  wing_instance_id: number;
}

export interface WingTags {
  code: string;
  id: Generated<number>;
}

export interface WingVersions {
  id: Generated<number>;
  mod_version_id: number;
  ship_id: number;
  wing_instance_id: number;
}

export interface WingWeaponGroups {
  id: Generated<number>;
  mode: string | null;
  wing_instance_id: number;
}

export interface WingWeapons {
  id: Generated<number>;
  weapon_id: number;
  weapon_slot_code: string;
  wing_weapon_group_id: number;
}

export interface DB {
  all_hullmod_instances: AllHullmodInstances;
  ammo_weapons: AmmoWeapons;
  beam_weapons: BeamWeapons;
  build_comments: BuildComments;
  build_hullmods: BuildHullmods;
  build_stats: BuildStats;
  build_weapons: BuildWeapons;
  build_wings: BuildWings;
  builds: Builds;
  built_in_hullmods: BuiltInHullmods;
  built_in_weapons: BuiltInWeapons;
  built_in_wings: BuiltInWings;
  damage_types: DamageTypes;
  entity_comments: EntityComments;
  entity_types: EntityTypes;
  hullmod_data: HullmodData;
  hullmod_instances: HullmodInstances;
  hullmod_tag_junction: HullmodTagJunction;
  hullmod_tags: HullmodTags;
  hullmod_ui_tag_junction: HullmodUiTagJunction;
  hullmod_ui_tags: HullmodUiTags;
  hullmod_versions: HullmodVersions;
  hullmods: Hullmods;
  images: Images;
  mod_versions: ModVersions;
  mods: Mods;
  mount_types: MountTypes;
  phase_stats: PhaseStats;
  proj_weapons: ProjWeapons;
  shield_stats: ShieldStats;
  shield_types: ShieldTypes;
  ship_descs: ShipDescs;
  ship_hint_junction: ShipHintJunction;
  ship_hints: ShipHints;
  ship_instances: ShipInstances;
  ship_logistic_stats: ShipLogisticStats;
  ship_positions: ShipPositions;
  ship_sizes: ShipSizes;
  ship_specs: ShipSpecs;
  ship_stats: ShipStats;
  ship_system_data: ShipSystemData;
  ship_system_desc: ShipSystemDesc;
  ship_system_descs: ShipSystemDescs;
  ship_system_instances: ShipSystemInstances;
  ship_system_versions: ShipSystemVersions;
  ship_systems: ShipSystems;
  ship_tag_junction: ShipTagJunction;
  ship_tags: ShipTags;
  ship_texts: ShipTexts;
  ship_versions: ShipVersions;
  ship_versions_full: ShipVersionsFull;
  ship_weapon_slots: ShipWeaponSlots;
  ships: Ships;
  users: Users;
  weapon_descs: WeaponDescs;
  weapon_group_junction: WeaponGroupJunction;
  weapon_groups: WeaponGroups;
  weapon_hint_junction: WeaponHintJunction;
  weapon_hints: WeaponHints;
  weapon_instances: WeaponInstances;
  weapon_sizes: WeaponSizes;
  weapon_specs: WeaponSpecs;
  weapon_stats: WeaponStats;
  weapon_tag_junction: WeaponTagJunction;
  weapon_tags: WeaponTags;
  weapon_texts: WeaponTexts;
  weapon_types: WeaponTypes;
  weapon_versions: WeaponVersions;
  weapon_versions_full: WeaponVersionsFull;
  weapons: Weapons;
  wing_data: WingData;
  wing_formations: WingFormations;
  wing_hullmods: WingHullmods;
  wing_instances: WingInstances;
  wing_roles: WingRoles;
  wing_tag_junction: WingTagJunction;
  wing_tags: WingTags;
  wing_versions: WingVersions;
  wing_weapon_groups: WingWeaponGroups;
  wing_weapons: WingWeapons;
}
