export interface WeaponVersionDTO {
    accuracy_str: string | null;
    ammo_per_second: string | null;
    autofire_accuracy_bonus: number | null;
    base_value: number | null;
    beam_speed: number | null;
    burst_delay: string | null;
    burst_size: string | null;
    chargedown: string | null;
    chargeup: string | null;
    custom_ancillary: string | null;
    custom_ancillary_hl: string | null;
    custom_primary: string | null;
    custom_primary_hl: string | null;
    damage_per_second: number | null;
    damage_per_shot: number | null;
    damage_type: string;
    damage_type_id: number;
    data_hash: string | null;
    display_name: string | null;
    emp: number | null;
    extra_arc_for_ai: number | null;
    flight_time: string | null;
    flux_per_second: string | null;
    flux_per_shot: string | null;
    groups: string[] | null;
    hints: string[] | null;
    hitpoints: number | null;
    impact: number | null;
    launch_speed: number | null;
    major: number;
    manufacturer: string | null;
    max_ammo: number | null;
    max_spread: string | null;
    min_spread: string | null;
    minor: number;
    mod_id: number;
    mod_name: string | null;
    mod_version_id: number;
    no_dps_tooltip: boolean | null;
    op_cost: number | null;
    patch: string;
    primary_role_str: string | null;
    proj_speed_str: string | null;
    reload_size: number | null;
    speed: number | null;
    spread_decay_per_second: string | null;
    spread_per_shot: string | null;
    tags: string[] | null;
    text1: string | null;
    text2: string | null;
    tracking_str: string | null;
    turn_rate: string | null;
    turn_rate_str: string | null;
    turret_gun_image_file_path: string | null;
    turret_image_file_path: string | null;
    weapon_code: string;
    weapon_id: number;
    weapon_instance_id: number;
    weapon_range: number | null;
    weapon_size: string;
    weapon_size_id: number;
    weapon_type: string;
    weapon_type_id: number;
    weapon_version_id: number;
}
